apiVersion: v1
kind: Service
metadata:
  name: kotak-ca-company
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /kotak_ca_company
  labels:
    app: kotak-ca-company
spec:
  ports:
    -  port: 8098
       targetPort: 8098
       protocol: TCP
  selector:
    app: kotak-ca-company
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: kotak-ca-company
data:
  application.properties: |-
    server.port=8098
        server.servlet.context-path=/middleware-apis
        spring.application.name=kotak_ca_pvt
        spring.main.allow-bean-definition-overriding=true
        #*********Redis configuration********#
        spring.redis.host=redis
        spring.redis.port=6379
        spring.redis.password=vahana@DEV
        #spring.redis.password=1234
        #*********Vahana Library*************#
        vps.api.designer-response-format=true
        vps.api.read-time-out=10000
        vps.api.connection-time-out=10000
        vps.api.proxy-server-host=127.0.0.1
        vps.api.proxy-server-port=8080
        vps.api.jks-cert-path=path-to-cert
        vps.api.jks-cert-pass=*****
        vps.api.dbes-endpoint=http://dbes:9007/dbes/service/dbexecutor/v1/execute
        vps.api.igw-endpoint=http://igw:9008/igw/executeOnlineProcess
        vps.api.hub-endpoint=https://vahanahub-uat.vahanacloud.com/vahanahub/execution/executeService
        vps.api.hub-secret=bbba4bd5-5b46-49a5-bfd6-33169ccc5355
        vps.api.service-endpoint=http://router:9000/router/engine/v1/gatewayProcessor
        vps.api.dms-endpoint=http://vahana-dms:9047/document-manager/
        vps.api.dms-storage-id=n969641a-1870-49ce-aca6-ca7e0528p9e9
        vps.api.logging-agent-url=http://logging-agent:9051/
        vps.api.logging-agent-enabled=true
        vps.api.otp-type=N
        vps.api.otp-length=6
        vps.api.otp-expiry-time=300
        vps.api.otp-cache-type=R
        #************Logging**************************#
        logging.level.org.springframework=INFO
        logging.level.com.decimaltech=INFO
        logging.level.com.zaxxer=DEBUG
        logging.level.root=ERROR
        #***************Database ORM*********************************#
        #***************Hikari Connection Pool***********************#
        #spring.datasource.hikari.connectionTimeout=20000
        #spring.datasource.hikari.maximumPoolSize=10
        #spring.datasource.hikari.poolName=HikariPoolZZZ
        #com.zaxxer.hikari.housekeeping.periodMs=10

        #-------------------------Postgres Database Properties-------------------
        #spring.datasource.url= jdbc:postgresql://13.127.54.186:5432/vahana_preprod
        #spring.datasource.username= postgres
        #spring.datasource.password= postgres
        #spring.jpa.properties.hibernate.default_schema = "bfsi"

        spring.datasource.url = jdbc:postgresql://decimalcafkyc-rds-uat.cbojrqtvnjtt.ap-south-1.rds.amazonaws.com:5433/KOTAK_CA_PP
        spring.datasource.username=decimal_cafkyc_uat
        spring.datasource.password=Decimal@321
        spring.jpa.properties.hibernate.default_schema = "bfsi"
        #spring.datasource.driver-class-name=org.postgresql.Driver

        spring.datasource.hikari.maximumPoolSize=50
        spring.datasource.hikari.minimumIdle=10
        spring.datasource.hikari.connectionTimeout=30000
        spring.datasource.hikari.idleTimeout=60000
        spring.datasource.hikari.maxLifetime=60000



        #************************************************************#
        #Actuators
        management.endpoints.web.exposure.include=*
        management.endpoint.health.group.custom.show-components=always
        management.endpoint.health.group.custom.show-details=always
        #--------------------------------------------------------------------------
        #spring.jpa.open-in-view=false
        #spring.jpa.hibernate.ddl-auto=update
        spring.jpa.properties.hibernate.dialect=decimal.bfsicommonbackend.repository.MidPointPostgreSQLDialect
        #spring.jpa.show-sql=true
        default.page.number=1
        default.page.size=30
        #----------------------------------------------------------------------------
        client.dbdefid=MINI_PROJECT-CUTGA6MBH0:MINI_PROJECT-BJRKLHTSPJ:FEDERAL_CA
        #----------------------------------------------------------------------------
        eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
        eureka.instance.prefer-ip-address=true
        eureka.instance.lease-renewal-interval-in-seconds=2
        eureka.instance.lease-expiration-duration-in-seconds=5
        eureka.client.registry-fetch-interval-seconds=5
        spring.cloud.compatibility-verifier.enabled=false
        #-----------------------------------------------------------------------------
        isHttpTracingEnabled=true
        logging-agent-url=http://logging-agent:9051/
        print.logs.on.console = N
        #-----------------------------------------------------------------------------
        #sendSmsUrl=http://localhost:8097/middleware-apis/info_sendSms

        sendSmsUrl=http://kotak-pvt-BankAPI:8097/middleware-apis/info_sendSms
        ncifUrl=http://kotak-pvt-BankAPI:8097/middleware-apis/ncif-status
        bcifUrl=http://kotak-pvt-BankAPI:8097/middleware-apis/bcif-dedupe
        pannsdlUrl=http://kotak-pvt-BankAPI:8097/middleware-apis/revised-pan-nsdl
        sendSmsByTemplateId=http://kotak-pvt-BankAPI:8097/middleware-apis/sendSms
        dataReviewUrl=https://kotak-ca-decimal-uat.vahanacloud.com/kotak-pvt-ltd/#/
        sendSmsByTemplateId=http://kotak-pvt-BankAPI:8097/middleware-apis/sendSms


        kotak_ca_pvt.persistent.path: /kotak_ca_pvt_json_files/
        messageId=131312321312421
        templateId=1007713189959400821

        Send Sms Api Headers info
        send_sms_url_username=6b6f74616b6373
        send_sms_url_password=4b6f74616b4031323324
        send_sms_token_url=https://xrwv2l.api.infobip.com/auth/1/session
        send_sms_client_url=https://xrwv2l.api.infobip.com/sms/2/text/advanced
        send_sms_serverIp=10.10.2.88
        send_sms_serverPort=8080

        #POSTBACKURL
        postbackUrl_llp=https://kotak-ca-decimal-uat.vahanacloud.com/middleware-apis/getLlpDoc/
        postbackUrl_mca=https://kotak-ca-decimal-uat.vahanacloud.com/middleware-apis/getMcaDoc/

        #uploadDocument Paths

        sole.prop.document.upload.filepath=/kotak_ca_pvt_json_files/pdf/
        sole.prop.document.download.filepath=/kotak_ca_pvt_json_files/pdf_final/
        sole.prop1.document.upload.filename=SOLE_PROPAOF_V1.pdf
        sole.prop2.document.upload.filename=SP_V2.pdf
        aadhaarPhtPath=/kotak_ca_pvt_json_files/pdf_final/


        #FILE_NET_HEADERS
        client_secret=607dea35602e4c69a33f8210221d374e
        client_url=https://apigwuat.kotak.com:8443/v1/Filenet
        client_id=l7xx6498192b28ad49649b262d2f34a85cbf
        file_net_url=http://kotak-pvt-BankAPI:8097/middleware-apis/filenet


        #dmsurl = http://vahana-dms:9047/document-manager/
        #mdo_using_filter_url=http://vahana-dms:9047/document-manager/
    
        dmsurl = http://vahana-dms:9047/document-manager/download/v1/getDocumentsUsingIds
        mdo_using_filter_url=http://vahana-dms:9047/document-manager/search/v1/getMDOUsingFilters



        #KOTAK_CONFIGURATION
        kotak_ca.orgId=DECIMAL-CGT6BYPRBI
        kotak_ca.appId=KOTAK_CA-269EW37XAL
        kotak_ca.clientSecret=dc257dce-e665-4443-ba2c-6923a1913c8d
        service.gatewayProcessorUrl=http://router:9000/router/engine/v1/gatewayProcessor
        kotak_ca.storageid=n969641a-1870-49ce-aca6-ca7e0528p9e9
        kotak_ca.s3.certfile.path=/kotak_ca_pvt_json_files/pdf/file.p12
    
    
    
        #Company and LLP Doc Activation Key
        Comp_Llp_Key=Y
    
        #BCIF DEDUPE BYPASS
        DedupeCheck=N
    
        #MCA DATA CHECK KEY
        McaCheck=N
    
        #LLP URL
        LLP_URL = https://api.probe42.in/probe_reports_sandbox/llps/{pan}/reference-document?type=CoI&identifier_type=PAN
        x_api_key=9N5T8lpUUt3VaLmAMb89U6vV9ESLt9HFaGYgcK8i
        x_api_version=1.3
        BR_DOC_PATH.PATH=/kotak_ca_pvt_json_files/pdf/BR_DOC_FORMAT.docx
        
        Email_link=https://kotak-ca-decimal-uat.vahanacloud.com/pvt-app/#/email-verification?code=

        #Rest Template Connection Pool
         maxConnectionPerRoute=25
         maxHttpConnections=50
         readTimeOut=30000
         connectionTimeOut=30000

        spring.kafka.producer.bootstrap-servers = IP:PORT
        spring.kafka.producer.key-serializer = org.apache.kafka.common.serialization.StringSerializer
        spring.kafka.producer.value-serializer = decimal.logs.serializer.CustomSerializer
        spring.kafka.producer.properties.message.max.bytes = 100000000
        spring.kafka.producer.properties.max.request.size = 100000000
       

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kotak-ca-company
  name: kotak-ca-company
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kotak-ca-company
  template:
    metadata:
      labels:
        app: kotak-ca-company
    spec:
      containers:
        - name: kotak-ca-company
          image: 712693083859.dkr.ecr.ap-south-1.amazonaws.com/kotak_ca_company:DUAT_03_10-1.0.79
          env:
            - name: TZ
              value: Asia/Kolkata
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75.0 -XX:MaxMetaspaceSize=2048M -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC -XX:+UseStringDeduplication -Xms2048m -Xmx4096m"
          ports:
            - containerPort: 8098
             
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/deployment/
              name: kotak-ca-company-volume
            - name: kotak-ca-company-pvc-volume
              mountPath: /kotak_ca_pvt_json_files/
            - name: kotak-ca-company-pvc-volume
              mountPath: /kotak_ca_pvt_json_files/pdf
            - name: kotak-ca-company-pvc-volume
              mountPath: /kotak_ca_pvt_json_files/pdf_final
            - name: kotak-ca-company-pvc-volume
              mountPath: /usr/local/share/fonts
      restartPolicy: Always
      imagePullSecrets:
        - name: awslogin

      volumes:
        - configMap:
            name: kotak-ca-company
          name: kotak-ca-company-volume

        - name: kotak-ca-company-pvc-volume
          persistentVolumeClaim:
            claimName: kotak-ca-company-pvc-volume
      securityContext:
        runAsUser: 0
        fsGroup: 0

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  name: kotak-ca-company
spec:
  rules:
    - host:
      http:
        paths:
          - path: /middleware-apis/
            pathType: Prefix
            backend:
              service:
                name: kotak-ca-company
                port:
                  number: 8098
